
#### Gather training data from 2020 candidata for president of the US (republican party)
get-trump:
		python3 data_collection.py --url https://twitter.com/realDonaldTrump
get-walsh:
		python3 data_collection.py --url https://twitter.com/WalshFreedom
get-weld:
		python3 data_collection.py --url https://twitter.com/GovBillWeld

#### Gather training data from 2020 candidata for president of the US (democrtatic party)
get-bennet:
		python3 data_collection.py --url https://twitter.com/SenatorBennet
get-biden:
		python3 data_collection.py --url https://twitter.com/JoeBiden
get-bloomberg:
		python3 data_collection.py --url https://twitter.com/MikeBloomberg
get-booker:
		python3 data_collection.py --url https://twitter.com/CoryBooker
get-buttigieg:
		python3 data_collection.py --url https://twitter.com/PeteButtigieg
get-castro:
		python3 data_collection.py --url https://twitter.com/JulianCastro
get-delaney:
		python3 data_collection.py --url https://twitter.com/JohnDelaney
get-TulsiGabbard:
		python3 data_collection.py --url https://twitter.com/TulsiGabbard
get-amyklobuchar:
		python3 data_collection.py --url https://twitter.com/amyklobuchar
get-DevalPatrick:
		python3 data_collection.py --url https://twitter.com/DevalPatrick
get-SenSanders:
		python3 data_collection.py --url https://twitter.com/SenSanders
get-TomSteyer:
		python3 data_collection.py --url https://twitter.com/TomSteyer
get-SenWarren:
		python3 data_collection.py --url https://twitter.com/SenWarren
get-marwilliamson:
		python3 data_collection.py --url https://twitter.com/marwilliamson
get-AndrewYang:
		python3 data_collection.py --url https://twitter.com/AndrewYang



#### Where is out testing data?( should be the data coming from the future because it makes more sense.)

# wd only get 5 latest tweet in this day.

# train model
train:
		python3 train.py --model_name bert_ssc --dataset twitter